config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  as :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  end

  post 'games/:id' => 'games#show'
  match 'games/:id/check_answer' => 'games#check_answer', via: :post

  resources :games
  resources :users, only: ['show', 'index']
  

end

app/models/game.rb
class Game < ActiveRecord::Base
	include Problem

	belongs_to :user

	def increment_streak
		self.increment!(:streak, 1)
	end

	def open?
		self.open
	end

	def close
		self.update(open: false)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :games

	def update_highscore(number)
		n = number.to_i
		
		self.update(high_score: n) if n > high_score
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def require_user
    unless current_user
    	redirect_to login_path
      flash[:alert] = "You must be logged in to access that feature"
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_filter :require_user

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)
		
		if @game.save
			@game.update(user_id: current_user.id)
			redirect_to @game
		else
			flash[:alert] = "something went wrong! try making another game..."
			redirect_to :new
		end
	end

	def show
		@game = Game.find(params[:id])
		if @game.open?
			@game.new_problem
		else
			flash[:alert] = "Oops, you've stumbled into a closed game"
			redirect_to root_path
		end
	end

	def check_answer
		@game = Game.find(params[:id])

		if @game.compare(params[:answer], params[:problem_solution])
			flash[:success] = 'Correct!'
			@game.increment_streak
			redirect_to game_path(@game)
		else
			@game.close
			@game.user.update_highscore(@game.streak)
			flash[:alert] = 'Wrong...'
			redirect_to root_path
		end
	end

	private

	def game_params
		params.require(:game).permit(:streak, :user_id, :game_type)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	def create
		@user = User.find_by(email: params[:session][:email])

		if @user && @user.authenticate(params[:session][:password])
	  	session[:user_id] = @user.id
	  	flash[:success] = "we missed you, #{@user.username}"
	  	redirect_to root_path
		else
			flash[:alert] = "email & password do not match"
	  	render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = 'User created!'
			redirect_to root_path
		else
			flash[:alert] = 'Oops! Something went wrong...'
			render 'new'
		end
  end

  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
	def print_problem(problem_type)
		if problem_type == 'multiplication'
			p "#{@game.x} x #{@game.y}"
		else
			p"#{@game.x * @game.y} / #{@game.y}"
		end 
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def average_game(user)
		a = user.games.map { |game| game.streak }
		a.inject{ |sum, n| sum + n } / a.size
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/new.html.erb
<%= form_for @game do |f| %>

	<%= f.label :game_type, 'multiplication' %>
	<%= f.radio_button :game_type, 'multiplication' %>
	<%= f.label :game_type, 'division' %>
	<%= f.radio_button :game_type, 'division' %>

	<% f.hidden_field :user_id, value: current_user.id %>
	<%= f.submit 'New Game' %>
<% end %>

app/views/games/show.html.erb
<div class="center_text">

	<h3><%= print_problem(@game.game_type) + "?" %></h3><br/>

	<%= form_tag "#{@game.id}/check_answer" do %>
		<%= text_field_tag 'answer', nil, class: "text_input center_text", autofocus: true %><br/>

		<%= hidden_field_tag 'problem_solution', @game.solution(@game.game_type) %>

		<%= submit_tag 'Submit', class: 'button' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Math</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="size">
	<ul class="center_text">
		<% if user_signed_in? %>
			<li class="left"><%= link_to 'New Game', new_game_path %></li>
			<li style="padding-right:26px;"><%= link_to 'Home', root_path %></li>
			<li class="right"><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
		<% else %>
			<li class="left"><%= link_to 'Login', new_user_session_path %></li>
			<li><%= link_to 'Home', root_path %></li>
			<li class= "right"><%= link_to 'Signup', new_user_registration_path %></li>
		<% end %>
	</ul>
</header>

<% if !flash.empty? %>
  <% flash.keys.each do |k| %>
      <div class="<%= k %>">
          <%= flash[k] %>
      </div>
  <% end %>
<% end %>

<div class="body">
	<%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.username %>
	<%= user.high_score %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="body center_text">
	<%= form_for @user do |f| %>
		<p><%= f.label :username %></p>
		<%= f.text_field :username, class: "text_input" %>
		<br/>

		<p><%= f.label :email %></p>
		<%= f.email_field :email, class: "text_input" %>
		<br/>

		<p><%= f.label :password %></p>
		<%= f.password_field :password, class: "text_input" %>
		<br/>

		<%= f.submit "Submit", class: "button" %>

	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1><br/>
<p>high score: <%= @user.high_score %> || average game: <%= average_game(@user) %></p>

app/views/welcome/index.html.erb
<header>
	<h1>Lern Mth</h1>
</header>

<div>
	<p>is fun.</p><br/>
	<% if user_signed_in? %>
		<p><%= link_to 'View Profile', user_path(current_user) %></p>
	<% end %>
</div>